#made by AzureDev7

function clearlag():
    broadcast "&b&lCLEARLAG &7• &bMọi Item Rơi Ra Sẽ Bị Xóa Trong 5 Phút Sắp Tới"
    wait 5 minutes
    broadcast "&b&lCLEARLAG &7• &cĐã Xóa %size of dropped items% Items Rơi Ra"
    kill dropped items

command clearlag:
    aliases: cl
    permission: clearlag
    permission message: 4&l[ERROR] &7• &cYou do not have permission to execute this command!
    trigger:
        clearlag()

every 5 minutes:
    clearlag()
